(() => {
'use strict';
const chapters = window.QUIZ_CHAPTERS || [];
const app = document.getElementById('app');
const modalRoot = document.getElementById('modalRoot');
let ticker = null;
const DURATION_MS = 30 * 60 * 1000;

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmtTime(ms){ms=Math.max(0,ms);const t=Math.ceil(ms/1000),m=Math.floor(t/60),s=t%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function stateKey(id){return `qth_chapter_${id}_v1`;}
function loadState(id){try{return JSON.parse(localStorage.getItem(stateKey(id))||'null')}catch{return null}}
function saveState(id,state){localStorage.setItem(stateKey(id),JSON.stringify(state));}
function clearState(id){localStorage.removeItem(stateKey(id));}
function chapterById(id){return chapters.find(c=>c.id===Number(id));}
function route(){const h=location.hash.slice(1);if(!h||h==='home')return renderHome();const [page,id]=h.split('/');if(page==='intro')return renderIntro(id);if(page==='quiz')return renderQuiz(id);if(page==='result')return renderResult(id);renderHome();}
function setHash(h){location.hash=h;}
function stopTimer(){if(ticker){clearInterval(ticker);ticker=null;}}

function renderHome(){stopTimer();app.innerHTML=`<main class="shell"><section class="hero"><div class="chapter-kicker">Hệ thống ôn tập trắc nghiệm</div><h1>Quản trị học</h1><p>Chọn một chương để làm bài. Mỗi bài gồm 40 câu, thời gian 30 phút. Kết quả hiển thị điểm và phần xem lại chi tiết sau khi nộp.</p></section><section class="grid">${chapters.map(c=>{const s=loadState(c.id);let label='Làm bài';if(s?.status==='active')label='Tiếp tục bài';if(s?.status==='submitted')label='Xem kết quả';return `<article class="chapter-card"><div class="chapter-kicker">Chương ${c.id}</div><h2>${esc(c.title)}</h2><div class="meta-row"><span class="badge">40 câu</span><span class="badge">30 phút</span><span class="badge">Thang điểm 10</span></div><button class="btn btn-primary" data-open="${c.id}">${label}</button></article>`}).join('')}</section><div class="footer-note">Dữ liệu câu hỏi Chương 3–9 được giữ theo bộ tài liệu đã cung cấp.</div></main>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const id=b.dataset.open,s=loadState(id);if(s?.status==='active')setHash(`quiz/${id}`);else if(s?.status==='submitted')setHash(`result/${id}`);else setHash(`intro/${id}`);});}

function renderIntro(id){stopTimer();const c=chapterById(id);if(!c)return setHash('home');const existing=loadState(c.id);app.innerHTML=`<main class="shell"><section class="panel"><div class="chapter-kicker">Chương ${c.id}</div><h1>${esc(c.fullTitle)}</h1><div class="rules"><div class="rule"><strong>40 câu trắc nghiệm</strong> - phải trả lời đầy đủ trước khi chủ động nộp bài.</div><div class="rule"><strong>30 phút</strong> - đồng hồ bắt đầu khi bấm “Bắt đầu làm bài”.</div><div class="rule">Nếu hết 30 phút, hệ thống <strong>tự động nộp bài</strong> kể cả khi còn câu chưa trả lời.</div><div class="rule">Sau khi nộp, bạn được xem lại đáp án, giải thích và nội dung kiến thức của từng câu.</div></div>${existing?.status==='submitted'?'<div class="notice">Chương này đã có một kết quả được lưu trên trình duyệt. Bạn có thể xem lại hoặc làm lại từ đầu.</div>':''}<div class="actions"><button class="btn btn-secondary" id="backHome">← Quay lại</button>${existing?.status==='submitted'?'<button class="btn btn-secondary" id="viewOld">Xem kết quả cũ</button>':''}<button class="btn btn-primary" id="startBtn">Bắt đầu làm bài</button></div></section></main>`;document.getElementById('backHome').onclick=()=>setHash('home');if(document.getElementById('viewOld'))document.getElementById('viewOld').onclick=()=>setHash(`result/${c.id}`);document.getElementById('startBtn').onclick=()=>{const now=Date.now();saveState(c.id,{status:'active',startedAt:now,answers:{},submittedAt:null,autoSubmitted:false});setHash(`quiz/${c.id}`);};}

function renderQuiz(id){stopTimer();const c=chapterById(id);if(!c)return setHash('home');let s=loadState(c.id);if(!s||s.status!=='active')return setHash(`intro/${c.id}`);const endAt=s.startedAt+DURATION_MS;if(Date.now()>=endAt){submit(c,true);return;}app.innerHTML=`<header class="topbar"><div class="topbar-inner"><div class="brand">${esc(c.fullTitle)}</div><div class="timer" id="timer">30:00</div></div></header><main class="shell"><div class="quiz-title"><h1>${esc(c.fullTitle)}</h1><div id="progressText">Đã trả lời 0/40 câu</div><div class="progressbar"><span id="progressFill"></span></div></div><div class="quiz-layout"><section class="quiz-main" id="questionList">${c.questions.map(q=>questionHtml(q,s.answers[q.id])).join('')}</section><aside class="quiz-sidebar"><h3>Danh sách câu</h3><div class="q-grid">${c.questions.map(q=>`<button class="q-jump ${s.answers[q.id]?'answered':''}" data-jump="${q.id}">${String(q.id).padStart(2,'0')}</button>`).join('')}</div><div class="sidebar-legend">Ô xanh nhạt: đã trả lời.</div><div class="actions"><button class="btn btn-secondary" id="backHomeBtn">Trang chủ</button></div></aside></div><div class="submit-wrap"><button class="btn btn-primary" id="submitBtn">NỘP BÀI</button></div></main>`;
  document.querySelectorAll('input[type=radio][data-q]').forEach(inp=>inp.addEventListener('change',e=>{s=loadState(c.id);if(!s||s.status!=='active')return;s.answers[e.target.dataset.q]=e.target.value;saveState(c.id,s);updateProgress(c,s);document.querySelector(`[data-jump="${e.target.dataset.q}"]`)?.classList.add('answered');}));
  document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(`q-${b.dataset.jump}`)?.scrollIntoView({behavior:'smooth',block:'start'}));
  document.getElementById('submitBtn').onclick=()=>attemptSubmit(c);
  document.getElementById('backHomeBtn').onclick=()=>setHash('home');
  updateProgress(c,s);
  const tick=()=>{const rem=endAt-Date.now(),el=document.getElementById('timer');if(!el)return;el.textContent=fmtTime(rem);el.classList.toggle('warn',rem<=5*60*1000&&rem>60*1000);el.classList.toggle('danger',rem<=60*1000);if(rem<=0){stopTimer();submit(c,true);}};tick();ticker=setInterval(tick,500);
}
function questionHtml(q,chosen){return `<article class="question-card" id="q-${q.id}"><div class="q-head"><span class="q-num">Câu ${q.id}</span><span class="q-group">${esc(q.group)}</span></div><div class="q-text">${esc(q.question)}</div><div class="options">${'ABCD'.split('').map(l=>`<label class="option"><input type="radio" name="q${q.id}" data-q="${q.id}" value="${l}" ${chosen===l?'checked':''}><span class="option-letter">${l}.</span><span class="option-text">${esc(q.options[l])}</span></label>`).join('')}</div></article>`;}
function updateProgress(c,s){const n=Object.keys(s.answers||{}).length,p=Math.round(n/c.questions.length*100);const t=document.getElementById('progressText'),f=document.getElementById('progressFill');if(t)t.textContent=`Đã trả lời ${n}/${c.questions.length} câu`;if(f)f.style.width=p+'%';}
function attemptSubmit(c){const s=loadState(c.id);if(!s||s.status!=='active')return;const missing=c.questions.filter(q=>!s.answers[q.id]).map(q=>q.id);if(missing.length){showMissingModal(c,missing);return;}showConfirmModal(c);}
function showMissingModal(c,missing){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>Chưa thể nộp bài</h3><p>Bạn còn <strong>${missing.length} câu chưa trả lời</strong>. Vui lòng hoàn thành tất cả câu hỏi trước khi nộp.</p><div class="missing-list">Câu ${missing.join(', ')}</div><div class="actions"><button class="btn btn-secondary" id="closeModal">Tiếp tục làm bài</button><button class="btn btn-primary" id="gotoMissing">Đi đến câu chưa trả lời đầu tiên</button></div></div></div>`;document.getElementById('closeModal').onclick=closeModal;document.getElementById('gotoMissing').onclick=()=>{closeModal();document.getElementById(`q-${missing[0]}`)?.scrollIntoView({behavior:'smooth',block:'start'});};}
function showConfirmModal(c){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>Xác nhận nộp bài</h3><p>Bạn đã trả lời đủ 40 câu. Sau khi nộp bài sẽ không thể thay đổi đáp án.</p><div class="actions"><button class="btn btn-secondary" id="cancelSubmit">Kiểm tra lại</button><button class="btn btn-primary" id="confirmSubmit">Nộp bài</button></div></div></div>`;document.getElementById('cancelSubmit').onclick=closeModal;document.getElementById('confirmSubmit').onclick=()=>{closeModal();submit(c,false);};}
function closeModal(){modalRoot.innerHTML='';}
function submit(c,auto){stopTimer();let s=loadState(c.id);if(!s||s.status!=='active')return;const submittedAt=Date.now();let correct=0;for(const q of c.questions)if(s.answers[q.id]===q.answer)correct++;s={...s,status:'submitted',submittedAt,autoSubmitted:!!auto,correct,total:c.questions.length,score:Number((correct/c.questions.length*10).toFixed(2))};saveState(c.id,s);setHash(`result/${c.id}`);}

function renderResult(id){stopTimer();const c=chapterById(id),s=loadState(id);if(!c)return setHash('home');if(!s||s.status!=='submitted')return setHash(`intro/${c.id}`);const unanswered=c.questions.filter(q=>!s.answers[q.id]).length,incorrect=c.questions.length-s.correct-unanswered;const elapsed=Math.min(DURATION_MS,Math.max(0,s.submittedAt-s.startedAt));app.innerHTML=`<main class="shell"><section class="result-summary"><div class="chapter-kicker">Kết quả</div><h1>${esc(c.fullTitle)}</h1>${s.autoSubmitted?'<div class="notice">Hết 30 phút - hệ thống đã tự động nộp bài.</div>':''}<div class="score">${s.score.toFixed(2).replace('.',',')} / 10</div><div class="stats"><div class="stat"><span>Đúng</span><strong>${s.correct}/40</strong></div><div class="stat"><span>Sai</span><strong>${incorrect}</strong></div><div class="stat"><span>Chưa làm</span><strong>${unanswered}</strong></div><div class="stat"><span>Thời gian</span><strong>${fmtTime(elapsed)}</strong></div></div><div class="actions"><button class="btn btn-secondary" id="homeResult">Trang chủ</button><button class="btn btn-primary" id="retryBtn">Làm lại chương này</button></div></section><section><h2>Xem lại bài làm</h2><div class="filters"><button class="filter-btn active" data-filter="all">Tất cả (40)</button><button class="filter-btn" data-filter="correct">Đúng (${s.correct})</button><button class="filter-btn" data-filter="incorrect">Sai (${incorrect})</button>${unanswered?`<button class="filter-btn" data-filter="unanswered">Chưa làm (${unanswered})</button>`:''}</div><div id="reviewList">${c.questions.map(q=>reviewHtml(q,s.answers[q.id])).join('')}</div></section></main>`;
  document.getElementById('homeResult').onclick=()=>setHash('home');document.getElementById('retryBtn').onclick=()=>{clearState(c.id);setHash(`intro/${c.id}`);};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.review-card').forEach(card=>card.style.display=(f==='all'||card.dataset.status===f)?'block':'none');});
}
function reviewHtml(q,chosen){const status=!chosen?'unanswered':chosen===q.answer?'correct':'incorrect';return `<article class="review-card ${status}" data-status="${status}"><div class="q-head"><span class="q-num">Câu ${q.id}</span><span class="q-group">${status==='correct'?'Đúng':status==='incorrect'?'Sai':'Chưa trả lời'}</span></div><div class="q-text">${esc(q.question)}</div><div class="review-options">${'ABCD'.split('').map(l=>{const cls=l===q.answer?'correct-option':(l===chosen&&chosen!==q.answer?'wrong-selected':'');return `<div class="review-option ${cls}"><span class="review-label">${l}.</span><span class="option-text">${esc(q.options[l])}</span></div>`}).join('')}</div><div class="answer-box"><div class="box-title">Đáp án đúng</div><div><strong>${q.answer}.</strong> ${esc(q.options[q.answer])}</div></div><div class="explain-box"><div class="box-title">Giải thích</div><div>${esc(q.explanation)}</div></div><div class="content-box"><div class="box-title">Nội dung thuộc</div><div>${esc(q.content)}</div></div></article>`;}

window.addEventListener('hashchange',route);route();
})();
